### ISSUE TITLE
Type of cable 

### ISSUE THREAD

**Issue by pelatyre** [claes/rotel-web-client#2]
Hello I just came across this and will be building it soon.  I was curious which type of cable you used.    Do you require a USB to 9pin serial cable or any other type?   I prefer to not use 9pin I’d I do t have too.  Thanks

**Comment by claes** [comment]
I used a USB to 9 pin serial connector,  which registered as /dev/ttyUSB0. The 9 pin serial is unavoidable as that is what connects to the amplifier. Check that you have that port on your amplifier.

**Comment by pelatyre** [comment]
Seems that my model will not work.  I don’t have a 9 pin port on my unit. 

Thank you
